### ISSUE TITLE
Does not show available buses

### ISSUE THREAD

**Issue by Aishnab** [Sosal-star/collaboratory#15]
![image](https://github.com/Sosal-star/collaboratory/assets/119724469/e084e5c9-8d66-40ac-a0af-e198ade99f7a)

**Comment by SumanSinghBhujel** [comment]
![image](https://github.com/Sosal-star/collaboratory/assets/127733117/10609417-35fa-4cdd-8645-e4b3c93dbf1a)
Solved.
