### ISSUE TITLE
navigation bar does not work in this page.

### ISSUE THREAD

**Issue by Aishnab** [Sosal-star/collaboratory#19]
![image](https://github.com/Sosal-star/collaboratory/assets/119724469/b088849b-4dd4-46be-810d-0a78be50b4f5)

**Comment by Sakshyam-hub** [comment]
I have Removed the navigation links and added only back to home.
![image](https://github.com/Sosal-star/collaboratory/assets/119908783/f0b8f1fb-dac2-4ab2-8762-e8b0e0c035bb)
