### ISSUE TITLE
CSS in driver side not working

### ISSUE THREAD

**Issue by Aishnab** [Sosal-star/collaboratory#20]
![image](https://github.com/Sosal-star/collaboratory/assets/119724469/d9c74cdb-d807-458d-a2cb-56d59713d6ba)
🫥

**Comment by Sosal-star** [comment]
solved !!!
![issue 2](https://github.com/Sosal-star/collaboratory/assets/119725484/84de0a3a-257d-4022-9bd8-6030d5a696d2)
