### ISSUE TITLE
Please fix the logo in Station managers dashboard.

### ISSUE THREAD

**Issue by Aishnab** [Sosal-star/collaboratory#22]
![image](https://github.com/Sosal-star/collaboratory/assets/119724469/8c46fb58-75c5-467c-b7f7-f25e46c6f5bb)

**Comment by Sosal-star** [comment]
I have identified and fixed this issue.
![issue 1](https://github.com/Sosal-star/collaboratory/assets/119725484/31a65b56-06af-4706-ac6f-b53da360029f)
