### ISSUE TITLE
Error in mysql

### ISSUE THREAD

**Issue by Aishnab** [Sosal-star/collaboratory#23]
![image](https://github.com/Sosal-star/collaboratory/assets/119724469/cc94b186-76f6-4d79-880a-00d7d347b4de)

**Comment by SumanSinghBhujel** [comment]
![image](https://github.com/Sosal-star/collaboratory/assets/127733117/929547f3-8e9f-4066-af7f-ae9913db942b)
Issues in the MySQL have been solved.
