### ISSUE TITLE
Font consistency

### ISSUE THREAD

**Issue by Aishnab** [Sosal-star/collaboratory#6]
The visual presentation suffers from font disparity.

**Comment by Aishnab** [comment]
The customer dashboard utilizes a font family inconsistent with the overall system design.

**Comment by Sosal-star** [comment]
> The visual presentation suffers from font disparity.
The issue has been resolved.👍👍

**Comment by Sakshyam-hub** [comment]
I have made the fonts consistent by including fonts from google fonts and also changed the CSS to make the fonts merge well and go in a consistent manner. You can see my branch for the updated documentations.
